### ISSUE TITLE
Error running job: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by D3voz** [ostris/ai-toolkit#243]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes
You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes/No

## Result:
 - 0 completed jobs
 - 1 failure
========================================
Traceback (most recent call last):
  File "E:\ai-toolkit\run.py", line 90, in <module>
    main()
  File "E:\ai-toolkit\run.py", line 86, in main
    raise e
  File "E:\ai-toolkit\run.py", line 78, in main
    job.run()
  File "E:\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "E:\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1853, in run
    loss_dict = self.hook_train_loop(batch_list)
  File "E:\ai-toolkit\extensions_built_in\sd_trainer\SDTrainer.py", line 1659, in hook_train_loop
    loss = self.train_single_accumulation(batch)
  File "E:\ai-toolkit\extensions_built_in\sd_trainer\SDTrainer.py", line 1606, in train_single_accumulation
    noise_pred = self.predict_noise(
  File "E:\ai-toolkit\extensions_built_in\sd_trainer\SDTrainer.py", line 968, in predict_noise
    return self.sd.predict_noise(
  File "E:\ai-toolkit\toolkit\stable_diffusion_model.py", line 1871, in predict_noise
    noise_pred = self.unet(
  File "E:\ai-toolkit\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\ai-toolkit\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\ai-toolkit\venv\lib\site-packages\diffusers\models\transformers\transformer_flux.py", line 520, in forward
    encoder_hidden_states, hidden_states = self._gradient_checkpointing_func(
TypeError: 'NoneType' object is not callable
my_first_flux_lora_v1:   0%|                                                                  | 0/2000 [00:00<?, ?it/s]

The error comes from turning gradient checkpointing , on windows . 

Turning Gradient checkpointing off makes it go out of memory - Caching latents to disk: 100%|███████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Generating baseline samples before training
my_first_flux_lora_v1:   0%|                                     | 0/2000 [00:01<?, ?it/s, lr: 1.0e-04 loss: 5.966e-01]Error running job: CUDA out of memory. Tried to allocate 216.00 MiB. GPU 0 has a total capacity of 79.54 GiB of which 120.81 MiB is free. Of the allocated memory 70.52 GiB is allocated by PyTorch, and 1.05 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

========================================
Result:
 - 0 completed jobs
 - 1 failure
========================================

**Comment by D3voz** [comment]
Fixed it, by uninstalling diffuser and reinstalling it and going back to an older commit

**Comment by jhj0517** [comment]
@D3voz Can you keep it open until it is actually fixed in the repository?

**Comment by AfterHAL** [comment]
I got this error to.
Uninstalled "diffusers" with `pip uninstall diffusers`
-> Found existing installation: diffusers 0.33.0.dev0
-> Uninstalling diffusers-0.33.0.dev0:

and reinstalled with `pip install diffusers`
-> Installing collected packages: diffusers
-> Successfully installed diffusers-0.32.2

**Comment by D3voz** [comment]
I think the issue is caused by diffusers-0.33.0.dev0 .  Reinstalling diffuser with pip install diffusers fixes it.

**Comment by D3voz** [comment]
> [@D3voz](https://github.com/D3voz) Can you keep it open until it is actually fixed in the repository?

ok

**Comment by SAC020** [comment]
It's still not working in Colab

**Comment by goffy76** [comment]
> I got this error too. Uninstalled "diffusers" with `pip uninstall diffusers` -> Found existing installation: diffusers 0.33.0.dev0 -> Uninstalling diffusers-0.33.0.dev0:
> 
> and reinstalled with `pip install diffusers` -> Installing collected packages: diffusers -> Successfully installed diffusers-0.32.2

Works - thank you hero :-)

**Comment by SAC020** [comment]
> I think the issue is caused by diffusers-0.33.0.dev0 . Reinstalling diffuser with pip install diffusers fixes it.

workaround worked for me as well, but what needs to happen for the issue to be fixed at the source?

**Comment by jhj0517** [comment]
@SAC020 `ai-toolkit` installs `diffusers` from the source code, not from pypi (I guess to follow recent patches from `diffusers`), and some recent patches from `diffusers` caused incompatibility with `ai-toolkit`.

To fix this from source you can see #244

**Comment by SAC020** [comment]
> [@SAC020](https://github.com/SAC020) `ai-toolkit` installs `diffusers` from the source code, not from pypi (I guess to follow recent patches from `diffusers`), and some recent patches from `diffusers` caused incompatibility with `ai-toolkit`.
> 
> To fix this from source you can see [#244](https://github.com/ostris/ai-toolkit/pull/244)

Thank you for explaining and for the fix. I am not sure how will I know / how can I tell when the proposed change is merged into the main code, I am not very proficient with github

**Comment by eliohead** [comment]
In the Colab notebook, this issue is resolved by uninstalling and reinstalling diffusers. However, since this causes the session to restart and the variables to be lost, you should not restart from the first cell. Instead, restart from the cell where the HF tokens are set, otherwise, the old non-functional diffusers will be reinstalled again. [https://colab.research.google.com/drive/1r09aImgL1YhQsJgsLWnb67-bjTV88-W0](https://colab.research.google.com/drive/1r09aImgL1YhQsJgsLWnb67-bjTV88-W0)

**Comment by khurchla** [comment]
Downgrading to diffusers Version: 0.32.2 also resolved this error for me on RunPod today. I uninstalled and reinstalled it with pip from PyPI as others recommended. Thanks very much.

**Comment by Xhah2017** [comment]
> I got this error too.
> Uninstalled "diffusers" with pip uninstall diffusers
> -> Found existing installation: diffusers 0.33.0.dev0
> -> Uninstalling diffusers-0.33.0.dev0:
> 
> and reinstalled with pip install diffusers
> -> Installing collected packages: diffusers
> -> Successfully installed diffusers-0.32.2

@AfterHAL Thank you, saved me twice.

**Comment by SAC020** [comment]
I think it's been fixed at the source, out-of-the-box now it installs diffusers 0.32.2

**Comment by D3voz** [comment]
Fixed
