### ISSUE TITLE
Modified (device: cuda:0) in (train_lora_flux_24gb.yaml) to (device: cuda:3), but still tell me GPU 0 OOM.

### ISSUE THREAD

**Issue by Bocchi-NotLikeCodeVersion** [ostris/ai-toolkit#277]
Modified (device: cuda:0) in (train_lora_flux_24gb.yaml) to (device: cuda:3), but still tell me GPU 0 OOM. My GPU 0 and GPU 1 are running services, but GPU 3 is not running any services

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 39.38 GiB of which 3.81 MiB is free. Process 3774011 has 38.88 GiB memory in use. Including non-PyTorch memory, this process has 494.00 MiB memory in use. Of the allocated memory 62.54 MiB is allocated by PyTorch, and 17.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by pixelworship** [comment]
noticed the exact same thing. Setting up device in yaml used to work.

ChatGPT:

```Why your device: cuda:1 in the YAML didn’t work

Under the hood, AI‑Toolkit reads that device key in TrainJob.__init__ but never actually passes it into the model–loading routines (all of which call Accelerator() with no arguments).  By default, Accelerate always uses CUDA_VISIBLE_DEVICES (or the first GPU it sees) as “cuda:0”.  So unless you remap the visible devices or explicitly tell Accelerate which GPU to use, it will keep loading everything on what it thinks is “0”.```

Until this was resolved, ```export CUDA_VISIBLE_DEVICES=1``` worked for me to set my second device up for training. Hopefully this is fixed soon.
