### ISSUE TITLE
Problem for training WAN2.2 and Qwen Image OOM

### ISSUE THREAD

**Issue by rachidlamouchi** [ostris/ai-toolkit#506]
## This is for bugs only

Did you already ask [in the discord](https://discord.gg/VXmU2f5WEU)?

No

You verified that this is a bug and not a feature request or question by asking [in the discord](https://discord.gg/VXmU2f5WEU)?

Yes

## Describe the bug

Hi, I should mention that I'm not a developer and I don't know anything about the command line.

For the past few months, following an update, it's no longer possible to train WAN2.2 or Qwen image, with the error mentioned below. I've tried everything with Chatgpt and Gemini, but I've never succeeded. Today I saw an update and thought it would fix it, but no, the problem persists. I should also mention that the problem continues even with a 512 training run using a batch of 1.
I should also clarify that this isn't a VRAM issue, as I can train a Flux at 1024 with a batch size of 2 without any problems.

FOR WAN2.2 : 
CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

FOR QWEN IMAGE : 
CUDA out of memory. Tried to allocate 2.03 GiB. GPU 0 has a total capacity of 31.84 GiB of which 0 bytes is free. Of the allocated memory 29.69 GiB is allocated by PyTorch, and 138.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I'm using the "easy installation" version.

W11, Core i9 12900k, RTX5090, 64G RAM

**Comment by sadblisscreations** [comment]
Im having the same problem with Qwen. i used to be able to train a lora using my 5090, i followed all the steps shown on his video and it worked, i trained multiple lora's. then i stopped for a while and installed different operating systems etc...now im on arch and got the itch to train lora's again, i installed aitoolkit again but now im running out of memory, followed the same steps as shown in the video https://www.youtube.com/watch?v=gIngePLXcaw. Not sure whats happening. i did try on windows 11 and it only got to 40 steps before not working anymore and it stayed stuck on 40 steps

**Comment by R-S1978** [comment]
Same problem with Qwen 😞

**Comment by rachidlamouchi** [comment]
Several months to find the simplest and most illogical solution in the history of humankind.

All that was needed was to activate "Layer Offloading" and set both values ​​to 0%. 🫩

**Comment by entmike** [comment]
> Several months to find the simplest and most illogical solution in the history of humankind.
> 
> All that was needed was to activate "Layer Offloading" and set both values ​​to 0%. 🫩

Thank you.

**Comment by zz64** [comment]
> Several months to find the simplest and most illogical solution in the history of humankind.
> 
> All that was needed was to activate "Layer Offloading" and set both values ​​to 0%. 🫩

Not fix for me
```
CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 15.45 GiB of which 9.75 MiB is free. Including non-PyTorch memory, this process has 14.81 GiB memory in use. Of the allocated memory 14.65 GiB is allocated by PyTorch, and 16.46 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
Qwen-Image-2512
GPU 5060 ti (16G VRAM)
```
clip-anytorch             2.6.0
dctorch                   0.1.2
open_clip_torch           3.2.0
pytorch-fid               0.3.0
pytorch_optimizer         3.9.0
pytorch-wavelets          1.3.0
torch                     2.9.1+cu128
torch-optimi              0.3.3
torchao                   0.10.0
torchaudio                2.9.1+cu128
torchcodec                0.9.1
torchdiffeq               0.2.5
torchsde                  0.2.6
torchvision               0.24.1+cu128
```
Python 3.11.14
Debian 13
