### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by claylebeouf** [ostris/ai-toolkit#574]
Traceback (most recent call last):
  File "E:\loratrainer\ai-toolkit\run.py", line 120, in <module>
    main()
  File "E:\loratrainer\ai-toolkit\run.py", line 108, in main
    raise e
  File "E:\loratrainer\ai-toolkit\run.py", line 96, in main
    job.run()
  File "E:\loratrainer\ai-toolkit\jobs\ExtensionJob.py", line 22, in run
    process.run()
  File "E:\loratrainer\ai-toolkit\jobs\process\BaseSDTrainProcess.py", line 1565, in run
    self.sd.load_model()
  File "E:\loratrainer\ai-toolkit\toolkit\models\wan21\wan21.py", line 412, in load_model
    transformer = self.load_wan_transformer(
  File "E:\loratrainer\ai-toolkit\toolkit\models\wan21\wan21.py", line 377, in load_wan_transformer
    quantize_model(self, transformer)
  File "E:\loratrainer\ai-toolkit\toolkit\util\quantize.py", line 308, in quantize_model
    block.to("cpu", non_blocking=True)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\torch\nn\modules\module.py", line 1371, in to
    return self._apply(convert)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    module._apply(fn)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    module._apply(fn)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\torch\nn\modules\module.py", line 957, in _apply
    param_applied = fn(param)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\torch\nn\modules\module.py", line 1357, in convert
    return t.to(
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\optimum\quanto\tensor\qtensor.py", line 93, in __torch_function__
    return func(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\optimum\quanto\tensor\qbytes.py", line 130, in __torch_dispatch__
    return qdispatch(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\optimum\quanto\tensor\qbytes_ops.py", line 64, in _to_copy
    out_data = op(t._data, dtype=t._data.dtype, **kwargs)
  File "C:\ProgramData\miniconda3\envs\AIToolkit\lib\site-packages\torch\_ops.py", line 1255, in __call__
    return self._op(*args, **kwargs)
torch.AcceleratorError: CUDA error: out of memory
Search for `cudaErrorMemoryAllocation' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I am watching GPU memory usage and it get no where near the 24 gb when this error gets thrown.  Only occurs when trying to train wan2.1 LoRAs, using Wan2.1-T2V-14B-Diffusers.   Training Flux and Qwen have no issues.

**Comment by syscore64-cmyk** [comment]
Same Problem, one of the Update (after adding Layer Offloading (wan2.2)) total broken. Ever OOM older version works fine ... (worked version commit: f48d05a) but its very old and not support new models like Z)

**Comment by DaveosTRC** [comment]
I installed an update for ComfyUI a few weeks ago that triggered this error with WAN2.2, and using "--disable-smart-memory" stopped the error.

I've just installed a fresh conda environment in WSL with python 3.10.19 (iirc) and latest Windows Nvidia drivers (not sure if needed for WSL/Ubuntu?), and followed the ai-toolkit install instructions/install order, but then a few seconds into a Z-image-turbo-dedist training (I think it did about 3 steps) it throws this error.

I also have 24gb vram 3090 RTX.


Given the two different setups and tasks with this same error I'm assuming it's driver related, but I can't be sure how the WSL install got it's drivers. I've had it quite some time. I'm wondering if my drivers in the WSL Ubuntu need updating.

**Comment by gwshdude** [comment]
> I installed an update for ComfyUI a few weeks ago that triggered this error with WAN2.2, and using "--disable-smart-memory" stopped the error.
> 
> I've just installed a fresh conda environment in WSL with python 3.10.19 (iirc) and latest Windows Nvidia drivers (not sure if needed for WSL/Ubuntu?), and followed the ai-toolkit install instructions/install order, but then a few seconds into a Z-image-turbo-dedist training (I think it did about 3 steps) it throws this error.
> 
> I also have 24gb vram 3090 RTX.
> 
> Given the two different setups and tasks with this same error I'm assuming it's driver related, but I can't be sure how the WSL install got it's drivers. I've had it quite some time. I'm wondering if my drivers in the WSL Ubuntu need updating.

5090 here. I'm also getting this error with WAN2.2, where do you put --disable-smart-memory ? I use the GUI so I just start it by enabling the venv and then cd to the UI folder and running "npm run start", so I'm not sure where to put "--disable-smart-memory"

**Comment by statcom** [comment]
I had the same issue. In my observation, this error has something to do with using shared gpu memory instead of actual dedicated gpu memory. I was able to avoid this error with the following steps:

* Set layer_offloading true
* Set No system fallback with the following procedure

1. Open NVIDIA Control Panel.
2. Go to Manage 3D Settings -> Program Settings
4. Scroll down to CUDA - Sysmem Fallback Policy.
5. Change it from "Driver Default" to "Prefer No Sysmem Fallback".
6. Click Apply.

**Comment by nitro79sf** [comment]
I am running into the same issue when trying to train a Flux Dev 2 lora.

I am on a RTX 6000 Pro GPU with 96GB VRAM
and 96GB system RAM.
I have been successfully with training loras for Flux Dev, Qwen and ZImage, but can`t get it to work with Flux Dev 2.

I already tried changing the system fallback policy as mentioned above.
I also tried to update to the latest nvidia driver 582.08 and latest cuda toolkit 13.1
Still running into the same error:

Error running job: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

<img width="1821" height="117" alt="Image" src="https://github.com/user-attachments/assets/dfa4186e-7aee-40b7-b79b-75d12a0bc3e0" />

<img width="1294" height="340" alt="Image" src="https://github.com/user-attachments/assets/2accacb5-cbc0-4fd6-9f53-c464a5127e2a" />

**Comment by gabrielxcom** [comment]
> I am running into the same issue when trying to train a Flux Dev 2 lora.
> 
> I am on a RTX 6000 Pro GPU with 96GB VRAM and 96GB system RAM. I have been successfully with training loras for Flux Dev, Qwen and ZImage, but can`t get it to work with Flux Dev 2.
> 
> I already tried changing the system fallback policy as mentioned above. I also tried to update to the latest nvidia driver 582.08 and latest cuda toolkit 13.1 Still running into the same error:
> 
> Error running job: CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> <img alt="Image" width="1821" height="117" src="https://private-user-images.githubusercontent.com/250873511/529000829-dfa4186e-7aee-40b7-b79b-75d12a0bc3e0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY3Njc4OTIsIm5iZiI6MTc2Njc2NzU5MiwicGF0aCI6Ii8yNTA4NzM1MTEvNTI5MDAwODI5LWRmYTQxODZlLTdhZWUtNDBiNy1iNzliLTc1ZDEyYTBiYzNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyNlQxNjQ2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTJiMDhhYzA1YzRiYzQwNjU5YmNlNzdkODI1MDc2NTVjYWEzOGJlMTA2N2E2YjdjNmVhNTRlZDU2M2FjZmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dpa4OTcFJIwlP2s8xfIyHejjk9OtuqRsuckJ2UJB5t0"> <img alt="Image" width="1294" height="340" src="https://private-user-images.githubusercontent.com/250873511/529000834-2accacb5-cbc0-4fd6-9f53-c464a5127e2a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjY3Njc4OTIsIm5iZiI6MTc2Njc2NzU5MiwicGF0aCI6Ii8yNTA4NzM1MTEvNTI5MDAwODM0LTJhY2NhY2I1LWNiYzAtNGZkNi05ZjUzLWM0NjRhNTEyN2UyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTIyNlQxNjQ2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGNiYThhNWY5OTM4NzcwNWVkYTFhNDc2OWQ5NThkZTUwN2E1ZGRkNzM2OWRlOWI3MDg0NWQwY2Y2OGFkYTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2gNiorz2qWW81SSBcmj05XWNqJBrcZ-5IWPH4dF1okA">

,I have this exact issue, but trying to build a Chroma1-HD LoRA. Did you manage to fix it?

**Comment by wang153723482** [comment]
I am running into the same issue when trying to train a QwenImage lora.Bug wan2.2 is work.
It's so strange. The code has been updated to the latest version in the repository

**Comment by Sanook-AI** [comment]
same issue here. Where can I get older version of ostris AI-toolkit. It was working perfectly to train wan 2.2 Loras with a 5090 ?

**Comment by gmackall** [comment]
I didn't fully bisect, but for me https://github.com/ostris/ai-toolkit/commit/20dfe1b4d56bbcfe45b78234d473a90dd7d21ec6 is working, and https://github.com/ostris/ai-toolkit/commit/55b8b0e23e0a4328bf7ed3faef45b009a431e741 is not (has this error). That's a pretty small range to finish bisecting, if someone was interested (but I'm not, I just wanted to get it working).

**Comment by amida168** [comment]
I had this problem when I used the UI. I tried to modify the example under config/examples/train_lora_wan22_14b_24gb.yaml , and then it worked for me.

**Comment by ProTekk** [comment]
> I didn't fully bisect, but for me [20dfe1b](https://github.com/ostris/ai-toolkit/commit/20dfe1b4d56bbcfe45b78234d473a90dd7d21ec6) is working, and [55b8b0e](https://github.com/ostris/ai-toolkit/commit/55b8b0e23e0a4328bf7ed3faef45b009a431e741) is not (has this error). That's a pretty small range to finish bisecting, if someone was interested (but I'm not, I just wanted to get it working).

A revert of this commit has at least allowed me to start training on Flux.2 Klein

**Comment by samueletto7** [comment]
PROBLEM WITH MEMORY CRASHES AFTER SEVERAL SPIKES
debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
AMD Ryzen 7 1700 Eight-Core Processor, 3000 MHz, 8 cores, 16 logical processors
Installed physical memory (RAM): 40.0 GB
Total physical memory: 39.9 GB
Available physical memory: 12.8 GB
Total virtual memory: 99.0 GB
Available virtual memory: 36.7 GB
Swap file space: 59.1 GB

**Comment by BORICUAPR** [comment]
same with wan2.2 some workflows..  not all
